# Generated by Django 5.2 on 2025-05-02 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo del cliente.', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Contenido del comentario.')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el comentario')),
                ('client', models.ForeignKey(help_text='Cliente al que pertenece el comentario.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.client')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que hizo este comentario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
